remote_theme: CaptainIRS/hacker-plus-theme

title: th3g3ntl3m4n's Cybersecurity (jpfdevs cybersecurity)
author: th3g3ntl3m4n
description: Writeups for plataforms like Vulnlab, Hack The Box, Try Hack Me, and all things of offensive security 
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: 578-215-1978 # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: 54328 # Go to the HackTheBox site and copy your ID
thm_badge_no: 13082 # Go to https://tryhackme.com/profile -> Public Profile -> Get Badge ID
show_thm_htb_badges_in_nav: true
github_username: th3g3ntl3m4n84
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: 
twitch:
youtube: jpfdevscybersecurity7523
twitter: 
facebook:
instagram: jpfdevscybersec
reddit:
pinterest:
telegram:
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true